#!/bin/bash
pkg update -y &&
pkg upgrade -y &&
pkg install git wget x11-repo root-repo tigervnc xfce4 xfce4-goodies -y &&
pkg install  python3 dbus -y &&
curl -L https://raw.githubusercontent.com/bajrangCoder/websockify_rs/main/install.sh | bash &&
vncserver &&
touch ~/.vnc/xstartup &&
chmod +x ~/.vnc/xstartup &&
# Very Important Thing

cat > ~/.vnc/xstartup << 'EOF'
#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
startxfce4 &
EOF

# It's Optional

cat >> ~/.bashrc << 'EOF'
# Custom VNC server alias
alias vnc-on="vncserver :1"
EOF

cat >> ~/.bashrc << 'EOF'
# Custom VNC server alias
alias vnc-off="vncserver -kill :1"
EOF
